on:
  push:
    branches: [ ci/* ]
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      package-name: febioheat
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/develop",
          "version": "v4.3",
        }
    secrets: inherit
