on:
  push:
    branches:
      - 'ci/develop'
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/windows-reusable.yml@develop
    with:
      aws-ami-id: ami-0b18c665dbe9efa75
      aws-sg-id: sg-0ca7912782cf1538b
      aws-instance-type: c5a.8xlarge
      package-name: febioheat
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/develop",
          "version": "v4.3",
        }
    secrets: inherit
