on:
  #schedule:
  #  - cron: '00 7 * * *' #0630 UTC kick off full build and regression
  push:
    branches: [ ci/reusable-workflow-windows ]
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/windows-reusable.yml@reusable-worfklow-windows
    with:
      aws-ami-id: ami-0a29d4b08307a935f
      aws-sg-id: sg-0ca7912782cf1538b
      aws-instance-type: c5a.8xlarge
      runTests: false
      package-name: febioheat
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/reusable-workflow-windows",
          "version": "v4.3",
        }
    secrets: inherit
